enum MATTER_TYPE {
  YOUTUBE
  TEXT
  IMAGE
  URL
}

type Matter {
  id: ID
  title: String,
  matterType: MATTER_TYPE,
  matterReference: String,
  # user: USER,
}

type Query {
  matters(
    userId: String,
  ): [Matter]
}

type Mutation {
  createMatter(
    title: String,
    matterType: MATTER_TYPE,
    matterReference: String,
    userId: String,
  ): Matter
}
