enum FILE_TYPE {
  YOUTUBE
  TEXT
  URL
}

type File {
  id: ID
  name: String,
  fileType: FILE_TYPE,
  fileReference: String,
  # user: USER,
}

extend type Folder {
  files: [File]
}

type Query {
  files(
    userId: String,
  ): [File]
}

type Mutation {
  createFile(
    name: String!,
    fileType: FILE_TYPE!,
    fileReference: String!,
    userId: String!,
  ): File
}
