type Folder {
  id: ID
  name: String,
  # user: USER,
}

type Query {
  folders(
    userId: String,
  ): [Folder]
}

type Mutation {
  createFolder(
    name: String!,
    userId: String,
  ): Folder
  addFileToFolder(
    folderId: ID!,
    fileId: ID!,
  ): Folder,
}
